package com.xworkz.abstraction.runner;

import com.xworkz.abstraction.internal.*;
import com.xworkz.abstraction.external.*;

public class Runner {
    public static void main(String[] args) {
        Printer printer = new PrinterImpl();
        PrinterUser printerUser = new PrinterUser(printer);
        printerUser.execute();
        Scanner scanner = new ScannerImpl();
        ScannerUser scannerUser = new ScannerUser(scanner);
        scannerUser.execute();
        Monitor monitor = new MonitorImpl();
        MonitorUser monitorUser = new MonitorUser(monitor);
        monitorUser.execute();
        Speaker speaker = new SpeakerImpl();
        SpeakerUser speakerUser = new SpeakerUser(speaker);
        speakerUser.execute();
        Keyboard keyboard = new KeyboardImpl();
        KeyboardUser keyboardUser = new KeyboardUser(keyboard);
        keyboardUser.execute();
        Mouse mouse = new MouseImpl();
        MouseUser mouseUser = new MouseUser(mouse);
        mouseUser.execute();
        Camera camera = new CameraImpl();
        CameraUser cameraUser = new CameraUser(camera);
        cameraUser.execute();
        Projector projector = new ProjectorImpl();
        ProjectorUser projectorUser = new ProjectorUser(projector);
        projectorUser.execute();
        Router router = new RouterImpl();
        RouterUser routerUser = new RouterUser(router);
        routerUser.execute();
        Modem modem = new ModemImpl();
        ModemUser modemUser = new ModemUser(modem);
        modemUser.execute();
        Mic mic = new MicImpl();
        MicUser micUser = new MicUser(mic);
        micUser.execute();
        Tablet tablet = new TabletImpl();
        TabletUser tabletUser = new TabletUser(tablet);
        tabletUser.execute();
        Laptop laptop = new LaptopImpl();
        LaptopUser laptopUser = new LaptopUser(laptop);
        laptopUser.execute();
        Desktop desktop = new DesktopImpl();
        DesktopUser desktopUser = new DesktopUser(desktop);
        desktopUser.execute();
        Smartwatch smartwatch = new SmartwatchImpl();
        SmartwatchUser smartwatchUser = new SmartwatchUser(smartwatch);
        smartwatchUser.execute();
        Television television = new TelevisionImpl();
        TelevisionUser televisionUser = new TelevisionUser(television);
        televisionUser.execute();
        Fan fan = new FanImpl();
        FanUser fanUser = new FanUser(fan);
        fanUser.execute();
        AC ac = new ACImpl();
        ACUser acUser = new ACUser(ac);
        acUser.execute();
        Heater heater = new HeaterImpl();
        HeaterUser heaterUser = new HeaterUser(heater);
        heaterUser.execute();
        Bulb bulb = new BulbImpl();
        BulbUser bulbUser = new BulbUser(bulb);
        bulbUser.execute();
        Switch switch1 = new SwitchImpl();
        SwitchUser switchUser = new SwitchUser(switch1);
        switchUser.execute();
        Door door = new DoorImpl();
        DoorUser doorUser = new DoorUser(door);
        doorUser.execute();
        Window window = new WindowImpl();
        WindowUser windowUser = new WindowUser(window);
        windowUser.execute();
        Fridge fridge = new FridgeImpl();
        FridgeUser fridgeUser = new FridgeUser(fridge);
        fridgeUser.execute();
        Oven oven = new OvenImpl();
        OvenUser ovenUser = new OvenUser(oven);
        ovenUser.execute();
        Toaster toaster = new ToasterImpl();
        ToasterUser toasterUser = new ToasterUser(toaster);
        toasterUser.execute();
        Washer washer = new WasherImpl();
        WasherUser washerUser = new WasherUser(washer);
        washerUser.execute();
        Dryer dryer = new DryerImpl();
        DryerUser dryerUser = new DryerUser(dryer);
        dryerUser.execute();
        Pump pump = new PumpImpl();
        PumpUser pumpUser = new PumpUser(pump);
        pumpUser.execute();
        Valve valve = new ValveImpl();
        ValveUser valveUser = new ValveUser(valve);
        valveUser.execute();
        Sensor sensor = new SensorImpl();
        SensorUser sensorUser = new SensorUser(sensor);
        sensorUser.execute();
        Drone drone = new DroneImpl();
        DroneUser droneUser = new DroneUser(drone);
        droneUser.execute();
        Robot robot = new RobotImpl();
        RobotUser robotUser = new RobotUser(robot);
        robotUser.execute();
        Charger charger = new ChargerImpl();
        ChargerUser chargerUser = new ChargerUser(charger);
        chargerUser.execute();
        PowerBank powerbank = new PowerBankImpl();
        PowerBankUser powerbankUser = new PowerBankUser(powerbank);
        powerbankUser.execute();
        MonitorStand monitorstand = new MonitorStandImpl();
        MonitorStandUser monitorstandUser = new MonitorStandUser(monitorstand);
        monitorstandUser.execute();
        Tripod tripod = new TripodImpl();
        TripodUser tripodUser = new TripodUser(tripod);
        tripodUser.execute();
        Flashlight flashlight = new FlashlightImpl();
        FlashlightUser flashlightUser = new FlashlightUser(flashlight);
        flashlightUser.execute();
        Remote remote = new RemoteImpl();
        RemoteUser remoteUser = new RemoteUser(remote);
        remoteUser.execute();
        Alarm alarm = new AlarmImpl();
        AlarmUser alarmUser = new AlarmUser(alarm);
        alarmUser.execute();
        Bell bell = new BellImpl();
        BellUser bellUser = new BellUser(bell);
        bellUser.execute();
        Lock lock = new LockImpl();
        LockUser lockUser = new LockUser(lock);
        lockUser.execute();
        Keypad keypad = new KeypadImpl();
        KeypadUser keypadUser = new KeypadUser(keypad);
        keypadUser.execute();
        Wheel wheel = new WheelImpl();
        WheelUser wheelUser = new WheelUser(wheel);
        wheelUser.execute();
        Lever lever = new LeverImpl();
        LeverUser leverUser = new LeverUser(lever);
        leverUser.execute();
        Joystick joystick = new JoystickImpl();
        JoystickUser joystickUser = new JoystickUser(joystick);
        joystickUser.execute();
        Stand stand = new StandImpl();
        StandUser standUser = new StandUser(stand);
        standUser.execute();
        Board board = new BoardImpl();
        BoardUser boardUser = new BoardUser(board);
        boardUser.execute();
        Pad pad = new PadImpl();
        PadUser padUser = new PadUser(pad);
        padUser.execute();
        Device device = new DeviceImpl();
        DeviceUser deviceUser = new DeviceUser(device);
        deviceUser.execute();
    }
}